### ISSUE TITLE
when `internal` is fixed, inlining missing deps throws an error

### ISSUE THREAD

**Issue by jrson83** [hairyf/ptsup#5]
### Description

When adding an internal dep, which does not exist in `dependencies`, the following error happens:

```bash
> ptsup --entry=src/index.ts --clean --external=[] --internal=react

X X [[ERROR]ERROR ]Could not resolve "react" 

    src/index.ts:1:33:
Could not resolve "react"      1 │ export { default as React } from

    src/index.ts:1:33:
'react'      1 │ export { default as React } from
        ╵                                  'react'~~~~~~~
        ╵

  You can mark the path "react" as external to exclude it from the bundle, which will remove this
  error.

~~~~~~~

  You can mark the path "react" as external to exclude it from the bundle, which will remove this
  error.

D:\__projects\ptsup\bundle-test\nn\node_modules\.pnpm\esbuild@0.17.12\node_modules\esbuild\lib\main.js:1636
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
src/index.ts:1:33: ERROR: Could not resolve "react"
    at failureErrorWithLog (D:\__projects\ptsup\bundle-test\nn\node_modules\.pnpm\esbuild@0.17.12\node_modules\esbuild\lib\main.js:1636:15)
    at D:\__projects\ptsup\bundle-test\nn\node_modules\.pnpm\esbuild@0.17.12\node_modules\esbuild\lib\main.js:1048:25
    at D:\__projects\ptsup\bundle-test\nn\node_modules\.pnpm\esbuild@0.17.12\node_modules\esbuild\lib\main.js:993:52
    at buildResponseToResult (D:\__projects\ptsup\bundle-test\nn\node_modules\.pnpm\esbuild@0.17.12\node_modules\esbuild\lib\main.js:1046:7)
    at D:\__projects\ptsup\bundle-test\nn\node_modules\.pnpm\esbuild@0.17.12\node_modules\esbuild\lib\main.js:1075:16
    at responseCallbacks.<computed> (D:\__projects\ptsup\bundle-test\nn\node_modules\.pnpm\esbuild@0.17.12\node_modules\esbuild\lib\main.js:697:9)
    at handleIncomingPacket (D:\__projects\ptsup\bundle-test\nn\node_modules\.pnpm\esbuild@0.17.12\node_modules\esbuild\lib\main.js:752:9)
    at Socket.readFromStdout (D:\__projects\ptsup\bundle-test\nn\node_modules\.pnpm\esbuild@0.17.12\node_modules\esbuild\lib\main.js:673:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 33,
        file: 'src/index.ts',
        length: 7,
        line: 1,
        lineText: "export { default as React } from 'react'",
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "react" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "react"'
    }
  ],
  warnings: []
}

Node.js v18.14.0
 ELIFECYCLE  Command failed with exit code 1.
```

### Replicate 

> If exist, remove `lockfile` and `node_modules` folder before.

1. Clone the repo, switch branch, install & build:
```bash
git clone https://github.com/jrson83/node-ts-preset
cd node-ts-preset
git checkout ptsup

pnpm install
pnpm build
```

> It should build with no errors.

2. Remove from `package.json`:

```json
"dependencies": {
  "react": "18.2.0"
},
```

3. run `pnpm build`.

> It will throw the error.

**Comment by hairyf** [comment]
I cloned your project and did not reproduce this error on window. Are you running on macOS?

**Comment by hairyf** [comment]
I cloned your project and did not reproduce this error on window. Are you running on macOS?

**Comment by jrson83** [comment]
I'm on windows 11. Please try again with a build including the ptsup fix for #4.

**Comment by hairyf** [comment]
You can use the --external=react option to make the packaging program work properly without installing react, but you cannot use --internal=react, which will read non-existent modules, which is normal.

Would fixing #4 solve your problem? Because I don't quite understand this issue.

**Comment by jrson83** [comment]
I need to check this again, I can't remember exactly what was my problem. I will check my example again.

I actually want to include react inside my bundle. Do I need to add react to `dependencies` or `devDependencies` then?

**Comment by hairyf** [comment]
> I need to check this again, I can't remember exactly what was my problem. I will check my example again.
> 
> I actually want to include react inside my bundle. Do I need to add react to `dependencies` or `devDependencies` then?

Yes

**Comment by jrson83** [comment]
@hairyf closing this since I can't replicate neither with the new build.

Is it possible that you update the docs with the missing TypeScript options & command line options? (`internal`, `external`)
